### ISSUE TITLE
Can I Use Solar Tweaks?

### ISSUE THREAD

**Issue by Mrn157** [Weave-MC/Weave-Loader#12]
if yes, please give me instructions on how to do it. Thank you :)

**Comment by Zircta** [comment]
Go to the Settings page on Solar Tweaks, and find the "JVM Arguments" section and add -javaagent:{PathToWeaveJar} to the JVM arguments. The argument should look something like this `-javaagent:C:\Users\Zircta\Downloads\Weave-Loader-Agent-0.1.0.jar`, with your own path of course.

**Comment by Mrn157** [comment]
Thank You :)
