### ISSUE TITLE
Crashing for no reason.

### ISSUE THREAD

**Issue by ronrishadi** [Weave-MC/Weave-Loader#15]
Crashing for no reason.

**Comment by normaluser12354** [comment]
i think somethings wrong with the weave loader

**Comment by exejar** [comment]
Sorry for the late reply, is your issue fixed with the newest version of Weave Loader?

**Comment by Nilsen84** [comment]
Closed due to inactivity. Please open a new issue if you're still experiencing crashes on the latest version of weave.
