### ISSUE TITLE
How can I launch Lunar With a Custom JvmArg

### ISSUE THREAD

**Issue by TheXiaoma** [Weave-MC/Weave-Loader#16]
launch Lunar with -javaagent:$PATH_TO_AGENT appended to the JVM arguments

**Comment by betterclient** [comment]
LUNAR LAUNCHER INJECT

**Comment by JustAiden9** [comment]
or use a custom build of lunar client and put it in there!

**Comment by CubeWhy** [comment]
github.com/CubeWhy/LunarClient-CN try this

**Comment by exejar** [comment]
Weave-Loader is not intended to add additional command line arguments. It is used specifically for loading Weave mods.
