### ISSUE TITLE
Different mods

### ISSUE THREAD

**Issue by Darkmonkey55** [Weave-MC/Weave-Loader#21]
How do I find all the different mods that can be used with weavelauncher?

**Comment by Monmcgt** [comment]
> How do I find all the different mods that can be used with weavelauncher?

#mod-sharing channel in the Weave discord

**Comment by Darkmonkey55** [comment]
oh ok is that the only way? i dont have discord and not able to get it

**Comment by PianoPenguin471** [comment]
[RavenWeave](https://github.com/PianoPenguin471/RavenWeave) is a common one

**Comment by exejar** [comment]
We will be creating a website soon, and we might add a list of verified (safe) weave mods. For now, [The Weave Project](https://discord.gg/HkSnuWrErY) Discord is the only place to search for Weave mods.
