### ISSUE TITLE
Minecraft 1.20

### ISSUE THREAD

**Issue by imjoel** [Weave-MC/Weave-Loader#22]
Will MC 1.20 be supported?

**Comment by Tryflle** [comment]
Only 1.8.9 is supported at the moment, afaik there are no plans to port it to any other version anytime soon

**Comment by exejar** [comment]
What tryflle said is mostly true, we do plan on adding support for future versions after we have polished the basic functionality of Weave-Loader. There is no current ETA for when this will be
