### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by GR0UPHUGS** [Weave-MC/Weave-Loader#23]
Im not sure if its just me or for the whole mac version but i dont have any sounds ingame. Anyone knows how to fix it?

**Comment by exejar** [comment]
Sorry for the late reply, are you normally using a minecraft directory that's not the default ~/.minecraft?

**Comment by GR0UPHUGS** [comment]
Nope, i got it fixed. I started using terminal to launch weave with lunar-launcher-injector-mac and that fixed the issue.

**Comment by exejar** [comment]
Great to hear, closing this issue.
