### ISSUE TITLE
I can't run the file at all

### ISSUE THREAD

**Issue by TRex9981e** [Weave-MC/Weave-Loader#25]
I can't run the java file to load it in at all, whenever I try it would load then nothing would open.
I tried many different fixes with java and it still doesn't work so i was wondering if you guys can check up on that? I tried running different java file and it work so I am not sure if it my computer or the weave java file.

**Comment by TRex9981e** [comment]
> I can't run the java file to load it in at all, whenever I try it would load then nothing would open. I tried many different fixes with java and it still doesn't work so i was wondering if you guys can check up on that? I tried running different java file and it work so I am not sure if it my computer or the weave java file.
I tried a little more and i got it to open up like a black box and then quickly crashing if that help my case..

**Comment by Monmcgt** [comment]
Weave Loader is not a java application. It is meant to be loaded as a java agent. You can load java agents with [Lunar Launcher Inject](https://github.com/Nilsen84/lunar-launcher-inject). Consider joining the discord for faster response.

**Comment by exejar** [comment]
The discord link for The Weave Project is https://discord.gg/HkSnuWrErY
