### ISSUE TITLE
make a mods list

### ISSUE THREAD

**Issue by HierarchyMan** [Weave-MC/Weave-Loader#30]
we need a documentation of all recognised weave mods in a wiki

**Comment by Scherso** [comment]
That isn't possible really, it's up to the developers of the mod to make it public that there mod is available. In our [discord server](https://discord.gg/TCGBCznhTK) there are threads made by mod developers which include their mods and descriptions of them.

**Comment by 770grappenmaker** [comment]
Not related to this specific project really, so should probably close
