### ISSUE TITLE
[Request] 1.20.2 Support

### ISSUE THREAD

**Issue by CrazyWolf13** [Weave-MC/Weave-Loader#40]
Hi
Is there any ETA for 1.20.2 support?

And do I get the project right that I could inject any mod (specifically a freecam mod) into lunar client?

**Comment by Monmcgt** [comment]
There's no ETA, but we're working on it.

You can only inject weave mods, not forge, not fabric, and weave only supports 1.8.9 right now.

**Comment by CrazyWolf13** [comment]
> There's no ETA, but we're working on it.
> 
> You can only inject weave mods, not forge, not fabric, and weave only supports 1.8.9 right now.

Oh okay great!
Is there any list of weave mods?
I couldn't find any weave mod?!

**Comment by Monmcgt** [comment]
> > There's no ETA, but we're working on it.
> > You can only inject weave mods, not forge, not fabric, and weave only supports 1.8.9 right now.
> 
> Oh okay great! Is there any list of weave mods? I couldn't find any weave mod?!

There is in the discord server. Check out Weave-MC's README for the link.
