### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by SomeRandomGuy30** [Weave-MC/Weave-Loader#41]
doesn't inject any mod anymore

**Comment by Monmcgt** [comment]
How do you inject Weave?

**Comment by SomeRandomGuy30** [comment]
I used both weave manager and weave loader with lunar client inject, neither work anymore

**Comment by Monmcgt** [comment]
Launch Weave with Lunar Client Inject and send the latest log file in `C:\Users\YourName\.lunarclient\logs\game`. Thanks!

**Comment by Monmcgt** [comment]
for macs i think it's in `~/.lunarclient/logs/game`

**Comment by nongbaobao** [comment]
i have the same problem, and here's my logs
[1ab2f155-e608-4d24-9eca-181f81d2693f-master.log](https://github.com/Weave-MC/Weave-Loader/files/14235714/1ab2f155-e608-4d24-9eca-181f81d2693f-master.log)

**Comment by Monmcgt** [comment]
Now fixed in Weave-Loader v0.2.6. :smile:
