### ISSUE TITLE
lunar crashing when clicking relaunch with weave

### ISSUE THREAD

**Issue by eTNTdiscord** [Weave-MC/Weave-Loader#43]
as soon as i press relaunch with weave on the app to inject to lunar it suddenly crashes.
any help or fix?
![image_2024-04-21_210303314](https://github.com/Weave-MC/Weave-Loader/assets/84364590/ad4e6223-cd41-419a-824a-8f7722d15530)

**Comment by 770grappenmaker** [comment]
I believe you are using an outdated version of the Weave Manager.

**Comment by exejar** [comment]
Definitely an outdated Weave Manager, as we no longer prompt for relaunch. Please install the [latest version](https://github.com/Weave-MC/Weave-Manager/releases)
